# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/dbassigame
spring.datasource.username=postgres
spring.datasource.password=pierrette
server.port=8081
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create 
spring.jpa.show-sql=true

# JWT
jwt.secret=assigame_super_secret_key_2026_esgis_very_long_key
jwt.expiration=86400000
