# URL de connexion à la base de données PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5434/dbassigame
# Identifiants de connexion
spring.datasource.username=postgres
spring.datasource.password=pierrette
server.port=8081
# Driver PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver
# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
